//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRIUSWrapped
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://xmlns.example.com/1387387040469", ConfigurationName = "siriusPort")]
    public interface siriusPort
    {

        // CODEGEN : La génération du contrat de message depuis l'opération insereReglement n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action = "insereReglement", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        insereReglementResponse insereReglement(insereReglementRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "insereReglement", ReplyAction = "*")]
        System.Threading.Tasks.Task<insereReglementResponse> insereReglementAsync(insereReglementRequest request);

        // CODEGEN : La génération du contrat de message depuis l'opération recupAffectation n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action = "recupAffectation", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        recupAffectationResponse recupAffectation(recupAffectationRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "recupAffectation", ReplyAction = "*")]
        System.Threading.Tasks.Task<recupAffectationResponse> recupAffectationAsync(recupAffectationRequest request);

        // CODEGEN : La génération du contrat de message depuis l'opération supprimeReglement n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action = "supprimeReglement", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        supprimeReglementResponse supprimeReglement(supprimeReglementRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "supprimeReglement", ReplyAction = "*")]
        System.Threading.Tasks.Task<supprimeReglementResponse> supprimeReglementAsync(supprimeReglementRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class requete
    {

        private requeteDonneesGenerales donneesGeneralesField;

        private requeteDonneesEncaissement donneesEncaissementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public requeteDonneesGenerales donneesGenerales
        {
            get
            {
                return this.donneesGeneralesField;
            }
            set
            {
                this.donneesGeneralesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public requeteDonneesEncaissement donneesEncaissement
        {
            get
            {
                return this.donneesEncaissementField;
            }
            set
            {
                this.donneesEncaissementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class requeteDonneesGenerales
    {

        private string idSiriusField;

        private int idSocieteField;

        private string numSiteVirtuelField;

        private string profileAS400Field;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public int idSociete
        {
            get
            {
                return this.idSocieteField;
            }
            set
            {
                this.idSocieteField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string numSiteVirtuel
        {
            get
            {
                return this.numSiteVirtuelField;
            }
            set
            {
                this.numSiteVirtuelField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileAS400
        {
            get
            {
                return this.profileAS400Field;
            }
            set
            {
                this.profileAS400Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class requeteDonneesEncaissement
    {

        private string codeModeReglementField;

        private string commentaireField;

        private System.DateTime dateEcheanceField;

        private bool dateEcheanceFieldSpecified;

        private System.DateTime dateEmissionField;

        private bool dateEmissionFieldSpecified;

        private string emetteurField;

        private string idContratField;

        private string idNumPieceReferenceField;

        private string idPieceAffectationField;

        private decimal montantField;

        private string numChequeField;

        private string typePieceAffectationField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeModeReglement
        {
            get
            {
                return this.codeModeReglementField;
            }
            set
            {
                this.codeModeReglementField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string commentaire
        {
            get
            {
                return this.commentaireField;
            }
            set
            {
                this.commentaireField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime dateEcheance
        {
            get
            {
                return this.dateEcheanceField;
            }
            set
            {
                this.dateEcheanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateEcheanceSpecified
        {
            get
            {
                return this.dateEcheanceFieldSpecified;
            }
            set
            {
                this.dateEcheanceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime dateEmission
        {
            get
            {
                return this.dateEmissionField;
            }
            set
            {
                this.dateEmissionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateEmissionSpecified
        {
            get
            {
                return this.dateEmissionFieldSpecified;
            }
            set
            {
                this.dateEmissionFieldSpecified = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string emetteur
        {
            get
            {
                return this.emetteurField;
            }
            set
            {
                this.emetteurField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idContrat
        {
            get
            {
                return this.idContratField;
            }
            set
            {
                this.idContratField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idNumPieceReference
        {
            get
            {
                return this.idNumPieceReferenceField;
            }
            set
            {
                this.idNumPieceReferenceField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idPieceAffectation
        {
            get
            {
                return this.idPieceAffectationField;
            }
            set
            {
                this.idPieceAffectationField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal montant
        {
            get
            {
                return this.montantField;
            }
            set
            {
                this.montantField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string numCheque
        {
            get
            {
                return this.numChequeField;
            }
            set
            {
                this.numChequeField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string typePieceAffectation
        {
            get
            {
                return this.typePieceAffectationField;
            }
            set
            {
                this.typePieceAffectationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class reponse
    {

        private reponseErreur erreurField;

        private bool resultatField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public reponseErreur erreur
        {
            get
            {
                return this.erreurField;
            }
            set
            {
                this.erreurField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public bool resultat
        {
            get
            {
                return this.resultatField;
            }
            set
            {
                this.resultatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class reponseErreur
    {

        private string erreurCodeField;

        private string erreurTraceField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurCode
        {
            get
            {
                return this.erreurCodeField;
            }
            set
            {
                this.erreurCodeField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurTrace
        {
            get
            {
                return this.erreurTraceField;
            }
            set
            {
                this.erreurTraceField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class insereReglementRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement", Order = 0)]
        public requete requete;

        public insereReglementRequest()
        {
        }

        public insereReglementRequest(requete requete)
        {
            this.requete = requete;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class insereReglementResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement", Order = 0)]
        public reponse reponse;

        public insereReglementResponse()
        {
        }

        public insereReglementResponse(reponse reponse)
        {
            this.reponse = reponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class requete1
    {

        private string idSiriusField;

        private string profileAS400Field;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileAS400
        {
            get
            {
                return this.profileAS400Field;
            }
            set
            {
                this.profileAS400Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponse1
    {

        private object[] itemsField;

        private bool resultatField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("donneesAffectation", typeof(reponseDonneesAffectation), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("donneesGenerales", typeof(reponseDonneesGenerales), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("erreur", typeof(reponseErreur1), Order = 0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public bool resultat
        {
            get
            {
                return this.resultatField;
            }
            set
            {
                this.resultatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseDonneesAffectation
    {

        private reponseDonneesAffectationContrat contratField;

        private string commentaireField;

        private string emetteurField;

        private string idNumPieceEncaissementField;

        private string idNumPieceReferenceField;

        private string indicAffectEncaissementField;

        private decimal montantField;

        private bool montantFieldSpecified;

        private string numChequeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public reponseDonneesAffectationContrat contrat
        {
            get
            {
                return this.contratField;
            }
            set
            {
                this.contratField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string commentaire
        {
            get
            {
                return this.commentaireField;
            }
            set
            {
                this.commentaireField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string emetteur
        {
            get
            {
                return this.emetteurField;
            }
            set
            {
                this.emetteurField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idNumPieceEncaissement
        {
            get
            {
                return this.idNumPieceEncaissementField;
            }
            set
            {
                this.idNumPieceEncaissementField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idNumPieceReference
        {
            get
            {
                return this.idNumPieceReferenceField;
            }
            set
            {
                this.idNumPieceReferenceField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string indicAffectEncaissement
        {
            get
            {
                return this.indicAffectEncaissementField;
            }
            set
            {
                this.indicAffectEncaissementField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal montant
        {
            get
            {
                return this.montantField;
            }
            set
            {
                this.montantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montantSpecified
        {
            get
            {
                return this.montantFieldSpecified;
            }
            set
            {
                this.montantFieldSpecified = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string numCheque
        {
            get
            {
                return this.numChequeField;
            }
            set
            {
                this.numChequeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseDonneesAffectationContrat
    {

        private int clientContratField;

        private bool clientContratFieldSpecified;

        private int gestionnaireContratField;

        private bool gestionnaireContratFieldSpecified;

        private string idContratField;

        private string libelleGestionnaireField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public int clientContrat
        {
            get
            {
                return this.clientContratField;
            }
            set
            {
                this.clientContratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientContratSpecified
        {
            get
            {
                return this.clientContratFieldSpecified;
            }
            set
            {
                this.clientContratFieldSpecified = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public int gestionnaireContrat
        {
            get
            {
                return this.gestionnaireContratField;
            }
            set
            {
                this.gestionnaireContratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gestionnaireContratSpecified
        {
            get
            {
                return this.gestionnaireContratFieldSpecified;
            }
            set
            {
                this.gestionnaireContratFieldSpecified = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idContrat
        {
            get
            {
                return this.idContratField;
            }
            set
            {
                this.idContratField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string libelleGestionnaire
        {
            get
            {
                return this.libelleGestionnaireField;
            }
            set
            {
                this.libelleGestionnaireField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseDonneesGenerales
    {

        private string idSiriusField;

        private string profileAS400Field;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileAS400
        {
            get
            {
                return this.profileAS400Field;
            }
            set
            {
                this.profileAS400Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseErreur1
    {

        private string erreurCodeField;

        private string erreurTraceField;

        private string idSiriusField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurCode
        {
            get
            {
                return this.erreurCodeField;
            }
            set
            {
                this.erreurCodeField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurTrace
        {
            get
            {
                return this.erreurTraceField;
            }
            set
            {
                this.erreurTraceField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class recupAffectationRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment", Order = 0)]
        public requete1 requete;

        public recupAffectationRequest()
        {
        }

        public recupAffectationRequest(requete1 requete)
        {
            this.requete = requete;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class recupAffectationResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment", Order = 0)]
        public reponse1 reponse;

        public recupAffectationResponse()
        {
        }

        public recupAffectationResponse(reponse1 reponse)
        {
            this.reponse = reponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement")]
    public partial class requete2
    {

        private string idSiriusField;

        private string profileAS400Field;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileAS400
        {
            get
            {
                return this.profileAS400Field;
            }
            set
            {
                this.profileAS400Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement")]
    public partial class reponse2
    {

        private reponseErreur2 erreurField;

        private bool resultatField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public reponseErreur2 erreur
        {
            get
            {
                return this.erreurField;
            }
            set
            {
                this.erreurField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public bool resultat
        {
            get
            {
                return this.resultatField;
            }
            set
            {
                this.resultatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement")]
    public partial class reponseErreur2
    {

        private string erreurCodeField;

        private string erreurTraceField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurCode
        {
            get
            {
                return this.erreurCodeField;
            }
            set
            {
                this.erreurCodeField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurTrace
        {
            get
            {
                return this.erreurTraceField;
            }
            set
            {
                this.erreurTraceField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class supprimeReglementRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement", Order = 0)]
        public requete2 requete;

        public supprimeReglementRequest()
        {
        }

        public supprimeReglementRequest(requete2 requete)
        {
            this.requete = requete;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class supprimeReglementResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement", Order = 0)]
        public reponse2 reponse;

        public supprimeReglementResponse()
        {
        }

        public supprimeReglementResponse(reponse2 reponse)
        {
            this.reponse = reponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface siriusPortChannel : siriusPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class siriusPortClient : System.ServiceModel.ClientBase<siriusPort>, siriusPort
    {

        public siriusPortClient()
        {
        }

        public siriusPortClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public siriusPortClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public siriusPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public siriusPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        insereReglementResponse siriusPort.insereReglement(insereReglementRequest request)
        {
            return base.Channel.insereReglement(request);
        }

        public reponse insereReglement(requete requete)
        {
            insereReglementRequest inValue = new insereReglementRequest();
            inValue.requete = requete;
            insereReglementResponse retVal = ((siriusPort)(this)).insereReglement(inValue);
            return retVal.reponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<insereReglementResponse> siriusPort.insereReglementAsync(insereReglementRequest request)
        {
            return base.Channel.insereReglementAsync(request);
        }

        public System.Threading.Tasks.Task<insereReglementResponse> insereReglementAsync(requete requete)
        {
            insereReglementRequest inValue = new insereReglementRequest();
            inValue.requete = requete;
            return ((siriusPort)(this)).insereReglementAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        recupAffectationResponse siriusPort.recupAffectation(recupAffectationRequest request)
        {
            return base.Channel.recupAffectation(request);
        }

        public reponse1 recupAffectation(requete1 requete)
        {
            recupAffectationRequest inValue = new recupAffectationRequest();
            inValue.requete = requete;
            recupAffectationResponse retVal = ((siriusPort)(this)).recupAffectation(inValue);
            return retVal.reponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<recupAffectationResponse> siriusPort.recupAffectationAsync(recupAffectationRequest request)
        {
            return base.Channel.recupAffectationAsync(request);
        }

        public System.Threading.Tasks.Task<recupAffectationResponse> recupAffectationAsync(requete1 requete)
        {
            recupAffectationRequest inValue = new recupAffectationRequest();
            inValue.requete = requete;
            return ((siriusPort)(this)).recupAffectationAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        supprimeReglementResponse siriusPort.supprimeReglement(supprimeReglementRequest request)
        {
            return base.Channel.supprimeReglement(request);
        }

        public reponse2 supprimeReglement(requete2 requete)
        {
            supprimeReglementRequest inValue = new supprimeReglementRequest();
            inValue.requete = requete;
            supprimeReglementResponse retVal = ((siriusPort)(this)).supprimeReglement(inValue);
            return retVal.reponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<supprimeReglementResponse> siriusPort.supprimeReglementAsync(supprimeReglementRequest request)
        {
            return base.Channel.supprimeReglementAsync(request);
        }

        public System.Threading.Tasks.Task<supprimeReglementResponse> supprimeReglementAsync(requete2 requete)
        {
            supprimeReglementRequest inValue = new supprimeReglementRequest();
            inValue.requete = requete;
            return ((siriusPort)(this)).supprimeReglementAsync(inValue);
        }
    }
}