//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par wsdl, Version=4.8.3928.0.
// 

namespace WSDLSIELProxy
{
    // 
    // Ce code source a été automatiquement généré par wsdl, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "siriusPicoEndpointBinding", Namespace = "http://xmlns.example.com/1387387040469")]
    public partial class siriusPicoserviceserviceagent : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback insereReglementOperationCompleted;

        private System.Threading.SendOrPostCallback recupAffectationOperationCompleted;

        private System.Threading.SendOrPostCallback supprimeReglementOperationCompleted;

        /// <remarks/>
        public siriusPicoserviceserviceagent()
        {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["siriusPicoEndpointBinding"];
            if ((urlSetting != null))
            {
                this.Url = urlSetting;
            }
            else
            {
                this.Url = "http://localhost:19410/service/finances/i1/v1/paymentEndpoint";
            }
        }

        /// <remarks/>
        public event insereReglementCompletedEventHandler insereReglementCompleted;

        /// <remarks/>
        public event recupAffectationCompletedEventHandler recupAffectationCompleted;

        /// <remarks/>
        public event supprimeReglementCompletedEventHandler supprimeReglementCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("insereReglement", RequestElementName = "requete", RequestNamespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement", ResponseElementName = "reponse", ResponseNamespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("erreur")]
        public reponseErreur insereReglement(requeteDonneesGenerales donneesGenerales, requeteDonneesEncaissement donneesEncaissement, [System.Xml.Serialization.XmlAttributeAttribute()] out bool resultat)
        {
            object[] results = this.Invoke("insereReglement", new object[] {
                    donneesGenerales,
                    donneesEncaissement});
            resultat = ((bool)(results[1]));
            return ((reponseErreur)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegininsereReglement(requeteDonneesGenerales donneesGenerales, requeteDonneesEncaissement donneesEncaissement, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("insereReglement", new object[] {
                    donneesGenerales,
                    donneesEncaissement}, callback, asyncState);
        }

        /// <remarks/>
        public reponseErreur EndinsereReglement(System.IAsyncResult asyncResult, out bool resultat)
        {
            object[] results = this.EndInvoke(asyncResult);
            resultat = ((bool)(results[1]));
            return ((reponseErreur)(results[0]));
        }

        /// <remarks/>
        public void insereReglementAsync(requeteDonneesGenerales donneesGenerales, requeteDonneesEncaissement donneesEncaissement)
        {
            this.insereReglementAsync(donneesGenerales, donneesEncaissement, null);
        }

        /// <remarks/>
        public void insereReglementAsync(requeteDonneesGenerales donneesGenerales, requeteDonneesEncaissement donneesEncaissement, object userState)
        {
            if ((this.insereReglementOperationCompleted == null))
            {
                this.insereReglementOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsereReglementOperationCompleted);
            }
            this.InvokeAsync("insereReglement", new object[] {
                    donneesGenerales,
                    donneesEncaissement}, this.insereReglementOperationCompleted, userState);
        }

        private void OninsereReglementOperationCompleted(object arg)
        {
            if ((this.insereReglementCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insereReglementCompleted(this, new insereReglementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("recupAffectation", RequestElementName = "requete", RequestNamespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment", ResponseElementName = "reponse", ResponseNamespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("donneesAffectation", typeof(reponseDonneesAffectation))]
        [return: System.Xml.Serialization.XmlElementAttribute("donneesGenerales", typeof(reponseDonneesGenerales))]
        [return: System.Xml.Serialization.XmlElementAttribute("erreur", typeof(reponseErreur1))]
        public object[] recupAffectation([System.Xml.Serialization.XmlAttributeAttribute()] string idSirius, [System.Xml.Serialization.XmlAttributeAttribute()] string profileAS400, [System.Xml.Serialization.XmlAttributeAttribute()] out bool resultat)
        {
            object[] results = this.Invoke("recupAffectation", new object[] {
                    idSirius,
                    profileAS400});
            resultat = ((bool)(results[1]));
            return ((object[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginrecupAffectation(string idSirius, string profileAS400, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("recupAffectation", new object[] {
                    idSirius,
                    profileAS400}, callback, asyncState);
        }

        /// <remarks/>
        public object[] EndrecupAffectation(System.IAsyncResult asyncResult, out bool resultat)
        {
            object[] results = this.EndInvoke(asyncResult);
            resultat = ((bool)(results[1]));
            return ((object[])(results[0]));
        }

        /// <remarks/>
        public void recupAffectationAsync(string idSirius, string profileAS400)
        {
            this.recupAffectationAsync(idSirius, profileAS400, null);
        }

        /// <remarks/>
        public void recupAffectationAsync(string idSirius, string profileAS400, object userState)
        {
            if ((this.recupAffectationOperationCompleted == null))
            {
                this.recupAffectationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecupAffectationOperationCompleted);
            }
            this.InvokeAsync("recupAffectation", new object[] {
                    idSirius,
                    profileAS400}, this.recupAffectationOperationCompleted, userState);
        }

        private void OnrecupAffectationOperationCompleted(object arg)
        {
            if ((this.recupAffectationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recupAffectationCompleted(this, new recupAffectationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("supprimeReglement", RequestElementName = "requete", RequestNamespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement", ResponseElementName = "reponse", ResponseNamespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("erreur")]
        public reponseErreur2 supprimeReglement([System.Xml.Serialization.XmlAttributeAttribute()] string idSirius, [System.Xml.Serialization.XmlAttributeAttribute()] string profileAS400, [System.Xml.Serialization.XmlAttributeAttribute()] out bool resultat)
        {
            object[] results = this.Invoke("supprimeReglement", new object[] {
                    idSirius,
                    profileAS400});
            resultat = ((bool)(results[1]));
            return ((reponseErreur2)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginsupprimeReglement(string idSirius, string profileAS400, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("supprimeReglement", new object[] {
                    idSirius,
                    profileAS400}, callback, asyncState);
        }

        /// <remarks/>
        public reponseErreur2 EndsupprimeReglement(System.IAsyncResult asyncResult, out bool resultat)
        {
            object[] results = this.EndInvoke(asyncResult);
            resultat = ((bool)(results[1]));
            return ((reponseErreur2)(results[0]));
        }

        /// <remarks/>
        public void supprimeReglementAsync(string idSirius, string profileAS400)
        {
            this.supprimeReglementAsync(idSirius, profileAS400, null);
        }

        /// <remarks/>
        public void supprimeReglementAsync(string idSirius, string profileAS400, object userState)
        {
            if ((this.supprimeReglementOperationCompleted == null))
            {
                this.supprimeReglementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsupprimeReglementOperationCompleted);
            }
            this.InvokeAsync("supprimeReglement", new object[] {
                    idSirius,
                    profileAS400}, this.supprimeReglementOperationCompleted, userState);
        }

        private void OnsupprimeReglementOperationCompleted(object arg)
        {
            if ((this.supprimeReglementCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.supprimeReglementCompleted(this, new supprimeReglementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class requeteDonneesGenerales
    {

        private string idSiriusField;

        private int idSocieteField;

        private string numSiteVirtuelField;

        private string profileAS400Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int idSociete
        {
            get
            {
                return this.idSocieteField;
            }
            set
            {
                this.idSocieteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numSiteVirtuel
        {
            get
            {
                return this.numSiteVirtuelField;
            }
            set
            {
                this.numSiteVirtuelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileAS400
        {
            get
            {
                return this.profileAS400Field;
            }
            set
            {
                this.profileAS400Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class requeteDonneesEncaissement
    {

        private string codeModeReglementField;

        private string commentaireField;

        private System.DateTime dateEcheanceField;

        private bool dateEcheanceFieldSpecified;

        private System.DateTime dateEmissionField;

        private bool dateEmissionFieldSpecified;

        private string emetteurField;

        private string idContratField;

        private string idNumPieceReferenceField;

        private string idPieceAffectationField;

        private decimal montantField;

        private string numChequeField;

        private string typePieceAffectationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeModeReglement
        {
            get
            {
                return this.codeModeReglementField;
            }
            set
            {
                this.codeModeReglementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commentaire
        {
            get
            {
                return this.commentaireField;
            }
            set
            {
                this.commentaireField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime dateEcheance
        {
            get
            {
                return this.dateEcheanceField;
            }
            set
            {
                this.dateEcheanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateEcheanceSpecified
        {
            get
            {
                return this.dateEcheanceFieldSpecified;
            }
            set
            {
                this.dateEcheanceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime dateEmission
        {
            get
            {
                return this.dateEmissionField;
            }
            set
            {
                this.dateEmissionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateEmissionSpecified
        {
            get
            {
                return this.dateEmissionFieldSpecified;
            }
            set
            {
                this.dateEmissionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string emetteur
        {
            get
            {
                return this.emetteurField;
            }
            set
            {
                this.emetteurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idContrat
        {
            get
            {
                return this.idContratField;
            }
            set
            {
                this.idContratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idNumPieceReference
        {
            get
            {
                return this.idNumPieceReferenceField;
            }
            set
            {
                this.idNumPieceReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idPieceAffectation
        {
            get
            {
                return this.idPieceAffectationField;
            }
            set
            {
                this.idPieceAffectationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal montant
        {
            get
            {
                return this.montantField;
            }
            set
            {
                this.montantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numCheque
        {
            get
            {
                return this.numChequeField;
            }
            set
            {
                this.numChequeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typePieceAffectation
        {
            get
            {
                return this.typePieceAffectationField;
            }
            set
            {
                this.typePieceAffectationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/insertSettlement")]
    public partial class reponseErreur
    {

        private string erreurCodeField;

        private string erreurTraceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurCode
        {
            get
            {
                return this.erreurCodeField;
            }
            set
            {
                this.erreurCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurTrace
        {
            get
            {
                return this.erreurTraceField;
            }
            set
            {
                this.erreurTraceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseDonneesAffectation
    {

        private reponseDonneesAffectationContrat contratField;

        private string commentaireField;

        private string emetteurField;

        private string idNumPieceEncaissementField;

        private string idNumPieceReferenceField;

        private string indicAffectEncaissementField;

        private decimal montantField;

        private bool montantFieldSpecified;

        private string numChequeField;

        /// <remarks/>
        public reponseDonneesAffectationContrat contrat
        {
            get
            {
                return this.contratField;
            }
            set
            {
                this.contratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commentaire
        {
            get
            {
                return this.commentaireField;
            }
            set
            {
                this.commentaireField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string emetteur
        {
            get
            {
                return this.emetteurField;
            }
            set
            {
                this.emetteurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idNumPieceEncaissement
        {
            get
            {
                return this.idNumPieceEncaissementField;
            }
            set
            {
                this.idNumPieceEncaissementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idNumPieceReference
        {
            get
            {
                return this.idNumPieceReferenceField;
            }
            set
            {
                this.idNumPieceReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string indicAffectEncaissement
        {
            get
            {
                return this.indicAffectEncaissementField;
            }
            set
            {
                this.indicAffectEncaissementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal montant
        {
            get
            {
                return this.montantField;
            }
            set
            {
                this.montantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montantSpecified
        {
            get
            {
                return this.montantFieldSpecified;
            }
            set
            {
                this.montantFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numCheque
        {
            get
            {
                return this.numChequeField;
            }
            set
            {
                this.numChequeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseDonneesAffectationContrat
    {

        private int clientContratField;

        private bool clientContratFieldSpecified;

        private int gestionnaireContratField;

        private bool gestionnaireContratFieldSpecified;

        private string idContratField;

        private string libelleGestionnaireField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int clientContrat
        {
            get
            {
                return this.clientContratField;
            }
            set
            {
                this.clientContratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientContratSpecified
        {
            get
            {
                return this.clientContratFieldSpecified;
            }
            set
            {
                this.clientContratFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int gestionnaireContrat
        {
            get
            {
                return this.gestionnaireContratField;
            }
            set
            {
                this.gestionnaireContratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gestionnaireContratSpecified
        {
            get
            {
                return this.gestionnaireContratFieldSpecified;
            }
            set
            {
                this.gestionnaireContratFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idContrat
        {
            get
            {
                return this.idContratField;
            }
            set
            {
                this.idContratField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string libelleGestionnaire
        {
            get
            {
                return this.libelleGestionnaireField;
            }
            set
            {
                this.libelleGestionnaireField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseDonneesGenerales
    {

        private string idSiriusField;

        private string profileAS400Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileAS400
        {
            get
            {
                return this.profileAS400Field;
            }
            set
            {
                this.profileAS400Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/selectAssignment")]
    public partial class reponseErreur1
    {

        private string erreurCodeField;

        private string erreurTraceField;

        private string idSiriusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurCode
        {
            get
            {
                return this.erreurCodeField;
            }
            set
            {
                this.erreurCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurTrace
        {
            get
            {
                return this.erreurTraceField;
            }
            set
            {
                this.erreurTraceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idSirius
        {
            get
            {
                return this.idSiriusField;
            }
            set
            {
                this.idSiriusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://leasingsolutions.bnpparibas.com/PICO/sirius/v1/deleteSettlement")]
    public partial class reponseErreur2
    {

        private string erreurCodeField;

        private string erreurTraceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurCode
        {
            get
            {
                return this.erreurCodeField;
            }
            set
            {
                this.erreurCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erreurTrace
        {
            get
            {
                return this.erreurTraceField;
            }
            set
            {
                this.erreurTraceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void insereReglementCompletedEventHandler(object sender, insereReglementCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insereReglementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal insereReglementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public reponseErreur Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((reponseErreur)(this.results[0]));
            }
        }

        /// <remarks/>
        public bool resultat
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void recupAffectationCompletedEventHandler(object sender, recupAffectationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recupAffectationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal recupAffectationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public object[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }

        /// <remarks/>
        public bool resultat
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void supprimeReglementCompletedEventHandler(object sender, supprimeReglementCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class supprimeReglementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal supprimeReglementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public reponseErreur2 Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((reponseErreur2)(this.results[0]));
            }
        }

        /// <remarks/>
        public bool resultat
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }

}